### ISSUE TITLE
jsonc wont work

### ISSUE THREAD

**Issue by ctf0** [sunmorgus/vscode-json-editor#19]
first many thanx for this ext, it makes a big difference with large files, however atm jsonc always gives error when opened because

- comments are invalid in json 
- trailing comma is invalid in json

**Comment by SjoerdV** [comment]
@sunmorgus Wouldn't this be a feature? Might be worth while to add jsonc spec support:
https://komkom.github.io/

**Comment by sunmorgus** [comment]
It could be a feature,  it not as part of this particular extension. All I do is implement an instance of the jsoneditoronline component... you'd have to ask for the feature to be added there.
