### ISSUE TITLE
Black Background Does not work correctly

### ISSUE THREAD

**Issue by ido-ran** [sunmorgus/vscode-json-editor#2]
I've try to use this add-on but when VS Code is in dark theme the keys are also written in black which makes it very hard to see.
The yellow key is visible when I hover the key with my mouse. The rest of the keys are black on black.

![screen shot 2018-07-30 at 9 20 03](https://user-images.githubusercontent.com/187938/43380436-dcbd2be2-93d9-11e8-95a5-681ba3ce3d60.png)

**Comment by lulax666** [comment]
Same here

![image](https://user-images.githubusercontent.com/12414645/43402562-0b635302-93e1-11e8-83e6-486a5ca1bfa9.png)

**Comment by obambrough** [comment]
Switching 'Json Editor' to its dark theme ("vscode-json-editor.theme": "dark") helped (as opposed to changing my VS Code to a light theme.) But it would be nice if 'Json Editor' applied the existing VS Code theme to its underlying json editor.

**Comment by dlucazeau** [comment]
Hi
I have the same comments, and it would be nice if we can set color for elements of the tree view.
Thanks.

**Comment by sunmorgus** [comment]
Sorry for the lateness of it; however, version 0.2.1 _should_ resolve this.

**Comment by sunmorgus** [comment]
Unfortunately, no... you'll still have to switch to the dark theme manually, but the background should hopefully blend better now.

**Comment by FranklinYu** [comment]
All right. I created #6 to track that. Will do more research about how to do that.
