### ISSUE TITLE
Can't get the extension to work... 

### ISSUE THREAD

**Issue by dinmammas** [sunmorgus/vscode-json-editor#3]
How is this supposed to work?

It's installed just fine (like five times). Closed/opened VSCode at least as many times.
Open various JSON-files, edit and save.

No tree view in sight.

Using VSCode 1.26 for mac.

Best regards,
n00b

**Comment by obambrough** [comment]
When you have an open JSON file run the 'JSON Editor: Start JSON editor session' command from the command palette.

**Comment by dinmammas** [comment]
TY!
